---
name: hovershot
channels:
  - conda-forge

dependencies:
  - python

  # tests
  - pytest-cov
  - pytest

  # dev
  - bumpversion=0.5.3
  - nox

  # nox lint
  - black=25.1.0
  - mypy=1.16.1
  - pre-commit=4.2.0
  - ruff=0.11.13

  # dependencies
  - numpy
  - pyinstaller
  - pyobjc-framework-Cocoa
  - pip

  - pip:
    - opencv-python-headless
    - pyqt6